In [1]:
import numpy as np
import pandas as pd

Question 1: Version of Pandas


In [2]:
print(pd.__version__)

1.5.2


In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")

Question 2: Number of columns in the dataset

In [4]:
data.shape[1]

10

Question 3: Select columns with missing data 

In [5]:
data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Question 4: Number of unique values in the `ocean_proximity` column

In [6]:
len(data["ocean_proximity"].unique())

5

Question 5: Average value of the `median_house_value` for the houses near the bay

In [7]:
data[data["ocean_proximity"] == "NEAR BAY"]["median_house_value"].mean()

259212.31179039303

Question 6: Has the mean value changed after filling missing values? 

In [9]:
data["total_bedrooms"].mean()

537.8705525375618

In [10]:
data["total_bedrooms"].fillna(259212.312, inplace=True)

In [11]:
data["total_bedrooms"].mean()

3132.134572868217

Questions 7: Value of the last element of w?

In [12]:
sub_data = data[data["ocean_proximity"] == "ISLAND"][["housing_median_age", "total_rooms", "total_bedrooms"]]

In [13]:
X = np.array(sub_data)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [14]:
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [15]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [16]:
y = np.array([950, 1300, 800, 1000, 1300])

In [18]:
A = np.dot(XTX_inv, X.T)
w = np.dot(A, y)
w[-1]

5.6992294550655656